### ISSUE TITLE
I don't know what it is.

### ISSUE THREAD

**Issue by PUDGE133** [rby-blackruby/BetterSinkholes2#1]
This is the only plugin that does something with pocket dimension. So I'm posting it here.
Usually appears at the start of a match, but this is not accurate information.
![12414124](https://user-images.githubusercontent.com/47304666/88915443-f3fd8300-d26c-11ea-9a2a-1c32b1b2aab5.png)

**Comment by rby-blackruby** [comment]
Hello Tamago4a,

Thank you for reaching out to me.

This issue is not caused by BetterSinkholes as this plugin does **not** use Exiled Events and does **not** handle escaping from the pocket dimension.

Kind Regards,
rby-blackruby
